- name: Executar testes GraphQL com Pactum
  run: npx mocha ./test/**/*.test.js

on:
  push:
    branches:
      - m26
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes GraphQL com Pactum
        run: npm test
